name: communitysite
description: Flutter Community Website
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  jaspr: ^0.8.1

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
  lints: ^2.1.1
